title: Q/EST Quest
description: 量子インターネットを探求するチーム

url: "https://tkm-sano.github.io"   # 自分のユーザページ URL
baseurl: "/qest-quest"              # ← ここ超重要!!

timezone: Asia/Tokyo
markdown: kramdown

theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap