title: Q/EST Quest
description: 量子インターネットを探求するチーム

# URL for your GitHub Pages user/org site
url: "https://tkm-sano.github.io"

# Base path for this project site
baseurl: "/qest-quest"    # ルート公開に移行するときは "" に変更

timezone: Asia/Tokyo
markdown: kramdown

theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
