# Site config
titile: "Q/est"
url: "https://q-est.org"      # production URL (leave empty for local)
baseurl: ""                    # if served from a subpath, set like "/qest-quest_jekyll"

# Locale / build
timezone: Asia/Tokyo
lang: ja
markdown: kramdown

# Theme & plugins
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Defaults
defaults:
  - scope:
      path: ""
    values:
      lang: ja

# Include additional static paths
include:
  - assets/data
  - assets/.well-known

# Collections
collections:
  news:
    output: true
    permalink: /projects/:slug/
  activities:
    output: true
    permalink: /activities/:slug/